# Generated by Django 6.0.4 on 2026-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/')),
                ('file_extension', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
